# -*- coding: utf-8 -*-
"""TDE 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QzgDfKcro6ngnIMcCym6WoXLgv9KvNd9

TDE 1: Demonstração diagramas de Venn
S = {1,2,3,4,5,6,7,8,9,10} ---> {x | x é natural e menor/igual á 10}
Conjunto A = {2,4,6,8} ---> {x | x é natural, par e menor que 10}
Conjunto B = {1,2,3,5,7} ---> B = {x | x é primo e menor que 10}

Videos: https://youtu.be/4pCuAv9sus0
---
"""

import matplotlib.pyplot as plt
from matplotlib_venn import venn2

#A)
set1 = set([2,4,6,8])
set2 = set([1,2,3,5,7])
venn = venn2([set1,set2], ('Conjunto A', 'Conjunto B'))

plt.title('AuB')
venn.get_label_by_id('100').set_text('\n'.join(map(str,set1)))
venn.get_label_by_id('110').set_text('\n'.join(map(str,set1.union(set2))))
venn.get_label_by_id('010').set_text('\n'.join(map(str,set2)))
#Cor conjunto A
venn.get_patch_by_id('100').set_alpha(0.6)
venn.get_patch_by_id('100').set_facecolor('red')
venn.get_patch_by_id('100').set_edgecolor('black')
venn.get_patch_by_id('100').set_linestyle('-.')
venn.get_patch_by_id('100').set_linewidth(10)

#Cor conjunto operações
venn.get_patch_by_id('110').set_alpha(0.6)
venn.get_patch_by_id('110').set_facecolor('yellow')
venn.get_patch_by_id('110').set_edgecolor('black')
venn.get_patch_by_id('110').set_linestyle('-.')
venn.get_patch_by_id('110').set_linewidth(10)

#Cor conjunto B
venn.get_patch_by_id('010').set_alpha(0.6)
venn.get_patch_by_id('010').set_facecolor('green')
venn.get_patch_by_id('010').set_edgecolor('black')
venn.get_patch_by_id('010').set_linestyle('-.')
venn.get_patch_by_id('010').set_linewidth(10)

#plot
plt.show()

#B)
set1 = set([1,3,5,7,9,10])
set2 = set([4,6,8,9,10])
venn = venn2([set1,set2], ('Conjunto A', 'Conjunto B'))

plt.title('A\'uB\'')
venn.get_label_by_id('100').set_text('\n'.join(map(str,set1-set2)))
venn.get_label_by_id('110').set_text('\n'.join(map(str,set1.union(set2))))
venn.get_label_by_id('010').set_text('\n'.join(map(str,set2-set1)))
plt.axis('on')
#Cor conjunto A
venn.get_patch_by_id('100').set_alpha(0.6)
venn.get_patch_by_id('100').set_facecolor('#45AC7A')
venn.get_patch_by_id('100').set_edgecolor('black')
venn.get_patch_by_id('100').set_linestyle(':')
venn.get_patch_by_id('100').set_linewidth(5)

#Cor conjunto operações
venn.get_patch_by_id('110').set_alpha(0.6)
venn.get_patch_by_id('110').set_facecolor('#45ACA1')
venn.get_patch_by_id('110').set_edgecolor('black')
venn.get_patch_by_id('110').set_linestyle(':')
venn.get_patch_by_id('110').set_linewidth(5)

#Cor conjunto B
venn.get_patch_by_id('010').set_alpha(0.6)
venn.get_patch_by_id('010').set_facecolor('#459BAC')
venn.get_patch_by_id('010').set_edgecolor('black')
venn.get_patch_by_id('010').set_linestyle(':')
venn.get_patch_by_id('010').set_linewidth(5)

#plot
plt.show()

#C)
set1 = set([2,4,6,8])
set2 = set([1,2,3,5,7])
venn = venn2([set1,set2], ('Conjunto A', 'Conjunto B'))

plt.title('AnB')
venn.get_label_by_id('100').set_text('\n'.join(map(str,set1-set2)))
venn.get_label_by_id('110').set_text('\n'.join(map(str,set1&set2)))
venn.get_label_by_id('010').set_text('\n'.join(map(str,set2-set1)))
plt.axis('on')
#Cor conjunto A
venn.get_patch_by_id('100').set_alpha(0.6)
venn.get_patch_by_id('100').set_facecolor('pink')
venn.get_patch_by_id('100').set_edgecolor('black')
venn.get_patch_by_id('100').set_linestyle('--')
venn.get_patch_by_id('100').set_linewidth(10)

#Cor conjunto operações
venn.get_patch_by_id('110').set_alpha(0.6)
venn.get_patch_by_id('110').set_facecolor('green')
venn.get_patch_by_id('110').set_edgecolor('black')
venn.get_patch_by_id('110').set_linestyle('--')
venn.get_patch_by_id('110').set_linewidth(10)

#Cor conjunto B
venn.get_patch_by_id('010').set_alpha(0.6)
venn.get_patch_by_id('010').set_facecolor('blue')
venn.get_patch_by_id('010').set_edgecolor('black')
venn.get_patch_by_id('010').set_linestyle('--')
venn.get_patch_by_id('010').set_linewidth(10)

#plot
plt.show()

#D)
set1 = set([1,3,5,7,9,10])
set2 = set([4,6,8,9,10])
venn = venn2([set1,set2], ('Conjunto A', 'Conjunto B'))

plt.title('A\'nB\'')
venn.get_label_by_id('100').set_text('\n'.join(map(str,set1-set2)))
venn.get_label_by_id('110').set_text('\n'.join(map(str,set1&set2)))
venn.get_label_by_id('010').set_text('\n'.join(map(str,set2-set1)))
plt.axis('on')
#Cor conjunto A
venn.get_patch_by_id('100').set_alpha(0.6)
venn.get_patch_by_id('100').set_facecolor('red')
venn.get_patch_by_id('100').set_edgecolor('black')
venn.get_patch_by_id('100').set_linestyle('--')
venn.get_patch_by_id('100').set_linewidth(5)

#Cor conjunto operações
venn.get_patch_by_id('110').set_alpha(0.6)
venn.get_patch_by_id('110').set_facecolor('skyblue')
venn.get_patch_by_id('110').set_edgecolor('purple')
venn.get_patch_by_id('110').set_linestyle('--')
venn.get_patch_by_id('110').set_linewidth(5)

#Cor conjunto B
venn.get_patch_by_id('010').set_alpha(0.6)
venn.get_patch_by_id('010').set_facecolor('red')
venn.get_patch_by_id('010').set_edgecolor('black')
venn.get_patch_by_id('010').set_linestyle('--')
venn.get_patch_by_id('010').set_linewidth(5)

#plot
plt.show()

#E)
set1 = set([2,4,6,8])
set2 = set([4,6,8,9,10])
venn = venn2([set1,set2], ('Conjunto A', 'Conjunto B'))

plt.title('AnB\'')
venn.get_label_by_id('100').set_text('\n'.join(map(str,set1-set2)))
venn.get_label_by_id('110').set_text('\n'.join(map(str,set1&set2)))
venn.get_label_by_id('010').set_text('\n'.join(map(str,set2-set1)))
plt.axis('on')
#Cor conjunto A
venn.get_patch_by_id('100').set_alpha(0.6)
venn.get_patch_by_id('100').set_facecolor('brown')
venn.get_patch_by_id('100').set_edgecolor('salmon')
venn.get_patch_by_id('100').set_linestyle('-.')
venn.get_patch_by_id('100').set_linewidth(5)

#Cor conjunto operações
venn.get_patch_by_id('110').set_alpha(0.6)
venn.get_patch_by_id('110').set_facecolor('pink')
venn.get_patch_by_id('110').set_edgecolor('salmon')
venn.get_patch_by_id('110').set_linestyle('-.')
venn.get_patch_by_id('110').set_linewidth(5)

#Cor conjunto B
venn.get_patch_by_id('010').set_alpha(0.6)
venn.get_patch_by_id('010').set_facecolor('orange')
venn.get_patch_by_id('010').set_edgecolor('salmon')
venn.get_patch_by_id('010').set_linestyle('-.')
venn.get_patch_by_id('010').set_linewidth(5)

#plot
plt.show()

#F)
set1 = set([2,4,6,8])
set2 = set([1,2,3,5,7])
venn = venn2([set1,set2], ('Conjunto A', 'Conjunto B'))

plt.title('A\'nB')

venn.get_label_by_id('100').set_text('\n'.join(map(str,set1-set2)))
venn.get_label_by_id('110').set_text('\n'.join(map(str,set1&set2)))
venn.get_label_by_id('010').set_text('\n'.join(map(str,set2-set1)))
plt.axis('on')
#Cor conjunto A
venn.get_patch_by_id('100').set_alpha(0.6)
venn.get_patch_by_id('100').set_facecolor('skyblue')
venn.get_patch_by_id('100').set_edgecolor('black')
venn.get_patch_by_id('100').set_linestyle(':')
venn.get_patch_by_id('100').set_linewidth(5)

#Cor conjunto operações
venn.get_patch_by_id('110').set_alpha(0.6)
venn.get_patch_by_id('110').set_facecolor('purple')
venn.get_patch_by_id('110').set_edgecolor('black')
venn.get_patch_by_id('110').set_linestyle(':')
venn.get_patch_by_id('110').set_linewidth(5)

#Cor conjunto B
venn.get_patch_by_id('010').set_alpha(0.6)
venn.get_patch_by_id('010').set_facecolor('blue')
venn.get_patch_by_id('010').set_edgecolor('black')
venn.get_patch_by_id('010').set_linestyle(':')
venn.get_patch_by_id('010').set_linewidth(5)

#plot
plt.show()